### ISSUE TITLE
'make_link' does not work

### ISSUE THREAD

**Issue by frankystone** [aleray/mdx_semanticwikilinks#1]
When executing the example regarding 'make_link' i get the following error with 
python version 2.7.12
markdown version 2.6.5

>>> md = markdown.Markdown(extensions=['semanticwikilinks'], extension_configs={'semanticwikilinks' : [('make_link', make_rdfa)]})
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/kaputtnik/wlwebsite/lib/python2.7/site-packages/markdown/__init__.py", line 159, in __init__
    configs=kwargs.get('extension_configs', {}))
  File "/home/kaputtnik/wlwebsite/lib/python2.7/site-packages/markdown/__init__.py", line 185, in registerExtensions
    ext = self.build_extension(ext, configs.get(ext, {}))
  File "/home/kaputtnik/wlwebsite/lib/python2.7/site-packages/markdown/__init__.py", line 291, in build_extension
    return module.makeExtension(**configs)
TypeError: makeExtension() got an unexpected keyword argument 'make_link'

Hopefully someone is looking into this :-)

**Comment by frankystone** [comment]
With the attached diff all is working fine again.

[semanticwikilinks_diff.txt](https://github.com/aleray/mdx_semanticwikilinks/files/680830/semanticwikilinks_diff.txt)
